### ISSUE TITLE
UI ToDo List

### ISSUE THREAD

**Issue by ericnerby** [ericnerby/EffectsPedalsWrangler#2]
## General:
- [x] Check for help and quit everywhere in the program
- [x] In 'View Existing Pedals' and 'View Existing Boards', allow choosing of a pedal or board
- [x] Allow delete or edit options once a pedal or board is selected to view
- [ ] Cleanup UI throughout once everything is working
## Edit Board:
- [x] Show pedals on board in order
- [x] Allow reordering (additional fields to code in VersionedList class)
- [x] Show Presets and allow selection of a preset
## Preset View:
- [x] View all pedals with their settings simultaneously
- [x] Select pedal to edit
- [x] Allow changing of settings on pedal (implement IInteractiveEditable on Settings)
